INSERT INTO SYSTEMSETTING (SS_NAME, SS_VALUE) VALUES ('Currency2Points', 5);//10 euro->5points
INSERT INTO SYSTEMSETTING (SS_NAME, SS_VALUE) VALUES ('Points2Currency', 5);//10 points->5euro
INSERT INTO SYSTEMSETTING (SS_NAME, SS_VALUE) VALUES ('CreatingAccountPoints', 150);
INSERT INTO SYSTEMSETTING (SS_NAME, SS_VALUE) VALUES ('RefferalPoints', 100);
INSERT INTO SYSTEMSETTING (SS_NAME, SS_VALUE) VALUES ('RatingPoints', 50);
INSERT INTO SYSTEMSETTING (SS_NAME, SS_VALUE) VALUES ('ReviewPoints', 100);
INSERT INTO SYSTEMSETTING (SS_NAME, SS_VALUE) VALUES ('OfferTimeStored', 10);

INSERT INTO ACTIONENUM (AE_NAME) VALUES ('ACCOUNTCREATION');
INSERT INTO ACTIONENUM (AE_NAME) VALUES ('REFFERAL');
INSERT INTO ACTIONENUM (AE_NAME) VALUES ('LEVELACHIEVED');
INSERT INTO ACTIONENUM (AE_NAME) VALUES ('POINTSCOLLECTED');

INSERT INTO LEVEL (L_NAME, L_LOWERBOUND, L_UPPERBOUND) VALUES ('Bronze', 0, 500);
INSERT INTO LEVEL (L_NAME, L_LOWERBOUND, L_UPPERBOUND) VALUES ('Silver', 501, 1500);
INSERT INTO LEVEL (L_NAME, L_LOWERBOUND, L_UPPERBOUND) VALUES ('Gold', 1501, 2500);
INSERT INTO LEVEL (L_NAME, L_LOWERBOUND) VALUES ('Platinum', 2501);

INSERT INTO OFFER (O_NAME, O_TEXT, O_STARTDATE, O_ENDDATE) VALUES ('First offer', 'this is link to the offer', '2016-09-09', '2018-12-31');
INSERT INTO OFFER (O_NAME, O_TEXT, O_STARTDATE, O_ENDDATE) VALUES ('Second offer', 'this is link to the offer', '2016-09-09', '2018-12-31');
INSERT INTO OFFER (O_NAME, O_TEXT, O_STARTDATE, O_ENDDATE) VALUES ('Third offer', 'this is link to the offer', '2016-09-09', '2018-12-31');
INSERT INTO OFFER (O_NAME, O_TEXT, O_STARTDATE, O_ENDDATE) VALUES ('Fourth offer', 'this is link to the offer', '2016-09-09', '2018-12-31');
INSERT INTO OFFER (O_NAME, O_TEXT, O_STARTDATE, O_ENDDATE) VALUES ('Fifth offer', 'this is link to the offer', '2016-09-09', '2018-12-31');

INSERT INTO USER (U_NAME, U_SURNAME, U_MAIL, U_TOTALPOINTS, U_CURRENTPOINTS, U_LEVEL, U_REFFERALCODE, U_PASSWORD) VALUES ('John', 'Smith', 'johnsmith@mail.com', 350, 150, 'Bronze', 'hVgpZ0T5YR', 'welcome');
INSERT INTO USER (U_NAME, U_SURNAME, U_MAIL, U_TOTALPOINTS, U_CURRENTPOINTS, U_LEVEL, U_REFFERALCODE, U_PASSWORD) VALUES ('Jan', 'Kowalski', 'jankowalski@mail.com', 150, 150, 'Bronze', 'a4eod2oPHj', 'welcome');
INSERT INTO USER (U_NAME, U_SURNAME, U_MAIL, U_TOTALPOINTS, U_CURRENTPOINTS, U_LEVEL, U_REFFERALCODE, U_PASSWORD) VALUES ('James', 'Bond', 'jamesbond@mail.com', 1700, 1050, 'Gold', 'QUHtEwyeHS', 'welcome');

INSERT INTO OFFERUSERCONNECTION (U_ID, O_ID) VALUES (1, 1);
INSERT INTO OFFERUSERCONNECTION (U_ID, O_ID) VALUES (1, 3);
INSERT INTO OFFERUSERCONNECTION (U_ID, O_ID) VALUES (2, 4);
INSERT INTO OFFERUSERCONNECTION (U_ID, O_ID) VALUES (2, 3);
INSERT INTO OFFERUSERCONNECTION (U_ID, O_ID) VALUES (3, 1);
INSERT INTO OFFERUSERCONNECTION (U_ID, O_ID) VALUES (3, 5);

INSERT INTO SENDINGRULE (SR_OFFER_ID, ACTIONENUM_ID, SR_LOYALTYLEVEL_ID, SR_CURRENTPOINTS) VALUES (1, 1, 0, 0);//pamiętać że tu tylko jeden z parametrów
INSERT INTO SENDINGRULE (SR_OFFER_ID, ACTIONENUM_ID, SR_LOYALTYLEVEL_ID, SR_CURRENTPOINTS) VALUES (2, 2, 0, 0);
INSERT INTO SENDINGRULE (SR_OFFER_ID, ACTIONENUM_ID, SR_LOYALTYLEVEL_ID, SR_CURRENTPOINTS) VALUES (3, 3, 3, 0);
INSERT INTO SENDINGRULE (SR_OFFER_ID, ACTIONENUM_ID, SR_LOYALTYLEVEL_ID, SR_CURRENTPOINTS) VALUES (4, 3, 2, 0);
INSERT INTO SENDINGRULE (SR_OFFER_ID, ACTIONENUM_ID, SR_LOYALTYLEVEL_ID, SR_CURRENTPOINTS) VALUES (5, 4, 0, 512);

INSERT INTO REFERRAL (RL_USER_ID, RL_NEWUSER_MAIL, RL_DATE) VALUES (1, 'jankowalski@mail.com', '2017-11-30');

INSERT INTO RATING (RG_DATE, RG_USER_ID) VALUES ('2017-11-30', 1);
INSERT INTO RATING (RG_DATE, RG_USER_ID) VALUES ('2017-12-13', 1);
INSERT INTO RATING (RG_DATE, RG_USER_ID) VALUES ('2017-10-30', 1);

INSERT INTO REVIEW (RW_DATE, RW_USER_ID) VALUES ('2017-12-24', 1);
INSERT INTO REVIEW (RW_DATE, RW_USER_ID) VALUES ('2017-11-30', 1);
INSERT INTO REVIEW (RW_DATE, RW_USER_ID) VALUES ('2017-09-14', 1);

INSERT INTO SHOPTRANSACTION (T_PRICE, T_DATE, T_POINTSEARNED, T_POINTSSPENT, T_USER_ID) VALUES (150.0, '2017-11-30', 75, 0, 1);
INSERT INTO SHOPTRANSACTION (T_PRICE, T_DATE, T_POINTSEARNED, T_POINTSSPENT, T_USER_ID) VALUES (250.0, '2017-11-30', 125, 0, 1);
INSERT INTO SHOPTRANSACTION (T_PRICE, T_DATE, T_POINTSEARNED, T_POINTSSPENT, T_USER_ID) VALUES (50.0, '2017-11-30', 25, 100, 1);
INSERT INTO SHOPTRANSACTION (T_PRICE, T_DATE, T_POINTSEARNED, T_POINTSSPENT, T_USER_ID) VALUES (60.0, '2017-11-30', 30, 0, 1);