CREATE TABLE SYSTEMSETTING(
  SS_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SS_NAME VARCHAR(32) NOT NULL,
  SS_VALUE INT NOT NULL
);

CREATE TABLE ACTIONENUM(
  AE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  AE_NAME VARCHAR(16) NOT NULL
);

CREATE TABLE LEVEL(
  L_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  L_NAME VARCHAR(16) NOT NULL,
  L_LOWERBOUND INT NOT NULL,
  L_UPPERBOUND INT
);

CREATE TABLE OFFER(
  O_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  O_NAME VARCHAR(16) NOT NULL,
  O_TEXT VARCHAR(32) NOT NULL,
  O_STARTDATE DATE,
  O_ENDDATE DATE
);

CREATE TABLE USER(
  U_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  U_NAME VARCHAR(16),
  U_SURNAME VARCHAR(16),
  U_MAIL VARCHAR(32) NOT NULL,
  U_TOTALPOINTS BIGINT,
  U_CURRENTPOINTS INT,
  U_LEVEL VARCHAR(16),
  U_REFERRALCODE VARCHAR(16),
  U_PASSWORD VARCHAR(16) NOT NULL
);

CREATE TABLE OFFERUSERCONNECTION(
  C_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  U_ID BIGINT,
  O_ID BIGINT
);

CREATE TABLE SENDINGRULE(
  SR_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SR_OFFER_ID BIGINT,
  ACTIONENUM_ID BIGINT,
  SR_LOYALTYLEVEL_ID BIGINT,
  SR_CURRENTPOINTS INT
);

CREATE TABLE REFERRAL(
  RL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  RL_USER_ID BIGINT NOT NULL,
  RL_NEWUSER_MAIL VARCHAR(32) NOT NULL,
  RL_DATE DATE
);

CREATE TABLE RATING(
  RG_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  RG_DATE DATE,
  RG_USER_ID BIGINT NOT NULL
);

CREATE TABLE REVIEW(
  RW_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  RW_DATE DATE,
  RW_USER_ID BIGINT NOT NULL
);

CREATE TABLE SHOPTRANSACTION(
  T_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  T_PRICE DOUBLE NOT NULL,
  T_DATE DATE,
  T_POINTSEARNED INT,
  T_POINTSSPENT INT,
  T_USER_ID BIGINT NOT NULL
);



ALTER TABLE REVIEW ADD FOREIGN KEY (RW_USER_ID) REFERENCES USER(U_ID);
ALTER TABLE RATING ADD FOREIGN KEY (RG_USER_ID) REFERENCES USER(U_ID);
ALTER TABLE SHOPTRANSACTION ADD FOREIGN KEY (T_USER_ID) REFERENCES USER(U_ID);
ALTER TABLE SENDINGRULE ADD FOREIGN KEY (ACTIONENUM_ID) REFERENCES ACTIONENUM(AE_ID);
ALTER TABLE SENDINGRULE ADD FOREIGN KEY (SR_OFFER_ID) REFERENCES OFFER(O_ID);
ALTER TABLE OFFERUSERCONNECTION ADD FOREIGN KEY (U_ID) REFERENCES USER(U_ID);
ALTER TABLE OFFERUSERCONNECTION ADD FOREIGN KEY (O_ID) REFERENCES OFFER(O_ID);
ALTER TABLE REFERRAL ADD FOREIGN KEY (RL_USER_ID) REFERENCES USER(U_ID);